apiVersion: v1
kind: Service
metadata:
  name: {{ include "mindns.fullname" . }}
  labels:
    {{- include "mindns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns
      protocol: UDP
      name: dns
  {{- if .Values.service.ip }}
  loadBalancerIP: {{ .Values.service.ip }}
  {{- end }}
  selector:
    {{- include "mindns.selectorLabels" . | nindent 4 }}
