apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "atuin.selectorLabels" . | nindent 4 }}
  name: {{ include "atuin.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "8888"
      port: {{ .Values.atuin.port }}
      targetPort: 8888
  selector:
    {{- include "atuin.selectorLabels" . | nindent 4 }}
