apiVersion: apps/v1
kind: Deployment
metadata:
  name: atuin
  labels:
    {{- include "myspeed.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "myspeed.selectorLabels" . | nindent 6 }}
    spec:
      containers:
        - args:
            - server
            - start
          env:
            - name: ATUIN_DB_URI
              value: postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ include "atuin.fullname" . }}-postgres:5432/atuin
            - name: ATUIN_HOST
              value: 0.0.0.0
            - name: ATUIN_PORT
              value: "8888"
            - name: ATUIN_OPEN_REGISTRATION
              value: "{{ .Values.atuin.open_registration }}"
          image: ghcr.io/atuinsh/atuin:latest
          name: atuin
          ports:
            - containerPort: 8888
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /config
              name: atuin-config
      volumes:
        - name: atuin-config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-atuin-config
