apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "atuin.selectorLabels" . | nindent 4 }}
  name: {{ include "atuin.fullname" . }}-postgres
spec:
  type: ClusterIP
  selector:
    {{- include "atuin.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
