apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "atuin.selectorLabels" . | nindent 4 }}
  name: {{ .Release.Name }}-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
