postgres:
  image: postgres
  tag: 14
  storage: 300Mi
  username: atuin
  password:
  port: 5432

atuin:
  image: ghcr.io/atuinsh/atuin
  open_registration: true

service:
  type: ClusterIP
  port: 8888

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: atuin.local
      paths:
        - path: /
          pathType: ImplementationSpecific
