postgres:
  image: postgres
  tag: 14
  storage: 300Mi
  username: atuin
  password:
  port: 5432

atuin:
  image: ghcr.io/atuinsh/atuin:latest
  open_registration: true

service:
  type: NodePort

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: {{ .Release.Name }}.local
      paths:
        - path: /
          pathType: ImplementationSpecific
