apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adguard.fullname" . }}
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
data:
  AdGuardHome.yaml: |
      {{ with .Values.adguard }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
