apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bazzite-updater.fullname" . }}
data:
  config.yaml: |
    machines:
      {{- range $machine := .Values.machines }}
      {{- toYaml $machine | nindent 6 }}
      {{- end }}
