apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bazzite-updater.fullname" . }}
  labels:
    {{- include "bazzite-updater.labels" . | nindent 4 }}
data:
  config.yaml: |
    machines:
      {{ with .Values.machines }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
